// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.3
// source: icmpmsg.proto

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IcmpMsg_TYPE int32

const (
	IcmpMsg_PONG_PROTO       IcmpMsg_TYPE = 0
	IcmpMsg_PING_PROTO       IcmpMsg_TYPE = 8
	IcmpMsg_CLIENT_SEND_FLAG IcmpMsg_TYPE = 1
	IcmpMsg_SERVER_SEND_FLAG IcmpMsg_TYPE = 2
	IcmpMsg_MAGIC            IcmpMsg_TYPE = 47837
)

// Enum value maps for IcmpMsg_TYPE.
var (
	IcmpMsg_TYPE_name = map[int32]string{
		0:     "PONG_PROTO",
		8:     "PING_PROTO",
		1:     "CLIENT_SEND_FLAG",
		2:     "SERVER_SEND_FLAG",
		47837: "MAGIC",
	}
	IcmpMsg_TYPE_value = map[string]int32{
		"PONG_PROTO":       0,
		"PING_PROTO":       8,
		"CLIENT_SEND_FLAG": 1,
		"SERVER_SEND_FLAG": 2,
		"MAGIC":            47837,
	}
)

func (x IcmpMsg_TYPE) Enum() *IcmpMsg_TYPE {
	p := new(IcmpMsg_TYPE)
	*p = x
	return p
}

func (x IcmpMsg_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IcmpMsg_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_icmpmsg_proto_enumTypes[0].Descriptor()
}

func (IcmpMsg_TYPE) Type() protoreflect.EnumType {
	return &file_icmpmsg_proto_enumTypes[0]
}

func (x IcmpMsg_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IcmpMsg_TYPE.Descriptor instead.
func (IcmpMsg_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_icmpmsg_proto_rawDescGZIP(), []int{0, 0}
}

type IcmpMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Magic         IcmpMsg_TYPE           `protobuf:"varint,3,opt,name=magic,proto3,enum=IcmpMsg_TYPE" json:"magic,omitempty"`
	Flag          IcmpMsg_TYPE           `protobuf:"varint,4,opt,name=flag,proto3,enum=IcmpMsg_TYPE" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcmpMsg) Reset() {
	*x = IcmpMsg{}
	mi := &file_icmpmsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcmpMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcmpMsg) ProtoMessage() {}

func (x *IcmpMsg) ProtoReflect() protoreflect.Message {
	mi := &file_icmpmsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcmpMsg.ProtoReflect.Descriptor instead.
func (*IcmpMsg) Descriptor() ([]byte, []int) {
	return file_icmpmsg_proto_rawDescGZIP(), []int{0}
}

func (x *IcmpMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IcmpMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *IcmpMsg) GetMagic() IcmpMsg_TYPE {
	if x != nil {
		return x.Magic
	}
	return IcmpMsg_PONG_PROTO
}

func (x *IcmpMsg) GetFlag() IcmpMsg_TYPE {
	if x != nil {
		return x.Flag
	}
	return IcmpMsg_PONG_PROTO
}

var File_icmpmsg_proto protoreflect.FileDescriptor

const file_icmpmsg_proto_rawDesc = "" +
	"\n" +
	"\ricmpmsg.proto\"\xd6\x01\n" +
	"\aIcmpMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12#\n" +
	"\x05magic\x18\x03 \x01(\x0e2\r.IcmpMsg.TYPER\x05magic\x12!\n" +
	"\x04flag\x18\x04 \x01(\x0e2\r.IcmpMsg.TYPER\x04flag\"_\n" +
	"\x04TYPE\x12\x0e\n" +
	"\n" +
	"PONG_PROTO\x10\x00\x12\x0e\n" +
	"\n" +
	"PING_PROTO\x10\b\x12\x14\n" +
	"\x10CLIENT_SEND_FLAG\x10\x01\x12\x14\n" +
	"\x10SERVER_SEND_FLAG\x10\x02\x12\v\n" +
	"\x05MAGIC\x10\xdd\xf5\x02B\fZ\n" +
	"./;networkb\x06proto3"

var (
	file_icmpmsg_proto_rawDescOnce sync.Once
	file_icmpmsg_proto_rawDescData []byte
)

func file_icmpmsg_proto_rawDescGZIP() []byte {
	file_icmpmsg_proto_rawDescOnce.Do(func() {
		file_icmpmsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_icmpmsg_proto_rawDesc), len(file_icmpmsg_proto_rawDesc)))
	})
	return file_icmpmsg_proto_rawDescData
}

var file_icmpmsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_icmpmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_icmpmsg_proto_goTypes = []any{
	(IcmpMsg_TYPE)(0), // 0: IcmpMsg.TYPE
	(*IcmpMsg)(nil),   // 1: IcmpMsg
}
var file_icmpmsg_proto_depIdxs = []int32{
	0, // 0: IcmpMsg.magic:type_name -> IcmpMsg.TYPE
	0, // 1: IcmpMsg.flag:type_name -> IcmpMsg.TYPE
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_icmpmsg_proto_init() }
func file_icmpmsg_proto_init() {
	if File_icmpmsg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icmpmsg_proto_rawDesc), len(file_icmpmsg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_icmpmsg_proto_goTypes,
		DependencyIndexes: file_icmpmsg_proto_depIdxs,
		EnumInfos:         file_icmpmsg_proto_enumTypes,
		MessageInfos:      file_icmpmsg_proto_msgTypes,
	}.Build()
	File_icmpmsg_proto = out.File
	file_icmpmsg_proto_goTypes = nil
	file_icmpmsg_proto_depIdxs = nil
}
