name: Big Endian Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Go test inside s390x container
        run: |
          docker run --rm -t \
            --platform=linux/s390x \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            golang:1.24 \
            bash -c '
              set -e
              echo "=== Testing crypto/cryptonight/inter/aes ==="
              cd /workspace/crypto/cryptonight/inter/aes && go test -v
      
              echo "=== Testing crypto/cryptonight/inter/blake256 ==="
              cd /workspace/crypto/cryptonight/inter/blake256 && go test -v
          
              echo "=== Testing crypto/cryptonight/inter/groestl ==="
              cd /workspace/crypto/cryptonight/inter/groestl && go test -v
          
              echo "=== Testing crypto/cryptonight/inter/jh ==="
              cd /workspace/crypto/cryptonight/inter/jh && go test -v
          
              echo "=== Testing crypto/cryptonight/inter/ripemd160 ==="
              cd /workspace/crypto/cryptonight/inter/ripemd160 && go test -v
          
              echo "=== Testing crypto/cryptonight/inter/sha3 ==="
              cd /workspace/crypto/cryptonight/inter/sha3 && go test -v
          
              echo "=== Testing crypto/cryptonight/inter/skein ==="
              cd /workspace/crypto/cryptonight/inter/skein && go test -v
          
              echo "=== Testing crypto/cryptonight/ ==="
              cd /workspace/crypto/cryptonight/ && go test -v
          
              echo "=== Testing crypto/ ==="
              cd /workspace/crypto/ && go test -v
            '