name: Big Endian Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  big-endian-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU + Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static curl docker.io

      - name: Run Big Endian Test in s390x container
        run: |
          docker pull s390x/ubuntu:22.04
          docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace s390x/ubuntu:22.04 \
          bash -c "apt update && apt install -y golang && cd ./crypto/cryptonight && go test -v"